### ISSUE TITLE
BUG - Range change analysis threw undefined error

### ISSUE THREAD

**Issue by blabadi** [overture-stack/js-lectern-client#8]
An undefined error found in argo clinical service during data migration that root cause is referring to the change analyzer line:
https://github.com/overture-stack/js-lectern-client/blob/29c75ac204352d4824dda10c9c5595540a01e0c1/src/change-analyzer.ts#L198:L205

## Description

error:

```
error: error handler received error: Cannot read property 'push' of undefined {"stack":"TypeError: Cannot read property 'push' of undefined\n    at categorizeRestrictionChanges (/app/node_modules/@overturebio-stack/lectern-client/lib/change-analyzer.js:166:58)\n    at Object.exports.analyzeChanges (/app/node_modules/@overturebio-stack/lectern-client/lib/change-analyzer.js:101:21)\n    at /app/node_modules/@overturebio-stack/lectern-client/lib/change-analyzer.js:43:20\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/@overturebio-stack/lectern-client/lib/change-analyzer.js:23:58)\n    at processTicksAndRejections (internal/process/task_queues.js:82:5)"}
POST /dictionary/migration/run 500 225.851 ms - 74
TypeError: Cannot read property 'push' of undefined
    at categorizeRestrictionChanges (/app/node_modules/@overturebio-stack/lectern-client/lib/change-analyzer.js:166:58)
    at Object.exports.analyzeChanges (/app/node_modules/@overturebio-stack/lectern-client/lib/change-analyzer.js:101:21)
    at /app/node_modules/@overturebio-stack/lectern-client/lib/change-analyzer.js:43:20
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/@overturebio-stack/lectern-client/lib/change-analyzer.js:23:58)
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
error: error handler received error: A migration is already active {"stack":"Error: A migration is already active\n    at /app/dist/src/submission/migration/migration-manager.js:99:19\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/dist/src/submission/migration/migration-manager.js:42:58)\n    at processTicksAndRejections (internal/process/task_queues.js:82:5)"}
POST /dictionary/migration/dry-run-update 409 8.790 ms - 59
Error: A migration is already active
    at /app/dist/src/submission/migration/migration-manager.js:99:19
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/src/submission/migration/migration-manager.js:42:58)
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
```

In Argo lectern QA 
this change: 
https://github.com/icgc-argo/argo-dictionary/commit/92fb92be7f27a23816122ec7224269af021842c7

diff between 88.1 / 88.2 

```
  [
    "specimen.percent_stromal_cells",
    {
      "left": {
        "name": "percent_stromal_cells",
        "description": "Indicate a value, in decimals, that represents the percentage of reactive cells that are present in a malignant tumour specimen but are not malignant such as fibroblasts, vascular structures, etc.",
        "valueType": "number",
        "meta": {
          "dependsOn": "sample_registration.tumour_normal_designation",
          "notes": "",
          "displayName": "Percent Stromal Cells"
        },
        "restrictions": {
          "range": {
            "min": 0,
            "max": 0.1
          }
        }
      },
      "right": {
        "name": "percent_stromal_cells",
        "description": "Indicate a value, in decimals, that represents the percentage of reactive cells that are present in a malignant tumour specimen but are not malignant such as fibroblasts, vascular structures, etc.",
        "valueType": "number",
        "meta": {
          "dependsOn": "sample_registration.tumour_normal_designation",
          "notes": "",
          "displayName": "Percent Stromal Cells"
        },
        "restrictions": {
          "range": {
            "min": 0,
            "max": 1
          }
        }
      },
      "diff": {
        "restrictions": {
          "range": {
            "max": {
              "type": "updated",
              "data": 1
            }
          }
        }
      }
    }
  ],

```

**Comment by joneubank** [comment]
Changes were made and tests added. Closing.
